import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Admin Login' }).click();
  await page.getByPlaceholder('Email').click();
  await page.getByPlaceholder('Email').fill('raghu2308.dev@gmail.com');
  await page.getByPlaceholder('Email').press('Tab');
  await page.getByPlaceholder('Password').fill('123456789');
  await page.getByPlaceholder('Password').press('Enter');
  await page.getByRole('link', { name: 'Register Student' }).click();
  await page.getByPlaceholder('Student\'s Name').click();
  await page.getByPlaceholder('Student\'s Name').fill('Pravin');
  await page.getByPlaceholder('Student\'s Name').press('Tab');
  await page.getByPlaceholder('Student 6 digit UID ').fill('090599');
  await page.getByPlaceholder('Student 6 digit UID ').press('Tab');
  await page.getByPlaceholder('Student DOB').fill('1999-05-09');
  await page.getByPlaceholder('Student DOB').press('Tab');
  await page.getByPlaceholder('Student DOB').press('Tab');
  await page.getByPlaceholder('Student DOB').press('Tab');
  await page.getByPlaceholder('digits ID').click();
  await page.getByPlaceholder('digits ID').fill('1234554321123');
  await page.getByPlaceholder('digits ID').press('Tab');
  await page.getByPlaceholder('email@domain.com').fill('pravin@gmail.com');
  await page.getByPlaceholder('email@domain.com').press('Tab');
  await page.getByPlaceholder('+(***********)').fill('9876543210');
  await page.getByPlaceholder('+(***********)').press('Tab');
  await page.getByPlaceholder('Student\'s Father\'s Name').fill('Pravin');
  await page.getByPlaceholder('Student\'s Father\'s Name').press('Tab');
  await page.getByPlaceholder('digit Room No').fill('230');
  await page.getByPlaceholder('digit Room No').press('Tab');
  await page.getByPlaceholder('Hostel').press('Tab');
  await page.getByPlaceholder('Department').fill('BE');
  await page.getByPlaceholder('Department').press('Tab');
  await page.getByPlaceholder('Stream').fill('IT');
  await page.getByPlaceholder('20**').click();
  await page.getByPlaceholder('20**').fill('2023');
  await page.getByPlaceholder('20**').press('Tab');
  await page.getByPlaceholder('Student\'s Permenant Resident').fill('Chennai');
  await page.getByPlaceholder('Student\'s Permenant Resident').press('Tab');
  await page.getByPlaceholder('Give a Strong Password').fill('123456789');
  await page.getByPlaceholder('Give a Strong Password').press('Tab');
  await page.getByRole('button', { name: 'Register Student' }).press('Enter');
  await page.getByPlaceholder('+(***********)').click();
  await page.getByPlaceholder('+(***********)').fill('98765432101');
  await page.getByPlaceholder('+(***********)').press('Enter');
  await page.getByRole('link', { name: 'All Students' }).click();
  await page.getByText('Pravin').click();
});